tools:
    shell:
        allow:
            - cd *
            - cargo check
            - head *
            - grep *
            - tail *
            - mkdir *
            - cargo build *
            - ./target/release/wzllama *
            - ls *
            - cat *
            - tree *
            - find *
            - sort
            - readlink *
            - /bin/cat *
            - cargo test
            - cargo test *
            - echo *
            - mv *
            - rm *
            - rmdir *
            - sed *
            - ./target/debug/wzllama *
            - timeout 2 bash *
            - cargo search *
            - timeout 2 *
            - "true"
            - curl *
            - which ls
            - docker ps *
            - git status
            - git diff *
            - cargo doc *
            - xargs *
            - python3 *
            - strings *
            - cargo run *
            - sort *
            - read f
            - basename "$f"
            - cargo download *
            - cargo fetch
            - tr *
paths:
    allow:
        - path: /home/olivier/Ai/wzllama/src/**
          write: true
        - path: /home/olivier/Ai/wzllama/**
          write: true
