### Anything between here and the comment below will become the contents of the drop-in file

[Service]
Environment="OLLAMA_MODELS=/home/ollama"
Environment="OLLAMA_ORIGINS=*"

### Edits below this comment will be discarded